### Inspecting our arrays

In [2]:
import numpy as np

In [3]:
num_arr = np.array([1, 2, 3, 4])

In [5]:
# shape of array
num_arr.shape

(4,)

In [6]:
# number of elements in array
len(num_arr)

4

In [10]:
# finding data type
num_arr.dtype.name

'int64'

In [11]:
# converting an array
float_arr = np.array([1.2, 3.5, 7.0])
int_arr = float_arr.astype(int)
print(int_arr)
print(int_arr.dtype)

[1 3 7]
int64


### Ask for help

In [13]:
np.info(np.ndarray.shape)

Tuple of array dimensions.

The shape property is usually used to get the current shape of an array,
but may also be used to reshape the array in-place by assigning a tuple of
array dimensions to it.  As with `numpy.reshape`, one of the new shape
dimensions can be -1, in which case its value is inferred from the size of
the array and the remaining dimensions. Reshaping an array in-place will
fail if a copy is required.

.. warning::

    Setting ``arr.shape`` is discouraged and may be deprecated in the
    future.  Using `ndarray.reshape` is the preferred approach.

Examples
--------
>>> x = np.array([1, 2, 3, 4])
>>> x.shape
(4,)
>>> y = np.zeros((2, 3, 4))
>>> y.shape
(2, 3, 4)
>>> y.shape = (3, 8)
>>> y
array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])
>>> y.shape = (3, 6)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: total size of new array must b

# Array mathematics

#### Arithmetic Operations

In [14]:
a = np.array([1, 4, 6, 7])
b = np.array([3, 5, 3, 1])

In [22]:
# subtract
diff1 = a - b
print('diff1 =', diff1)
diff2 = np.subtract(a, b)
print('diff2 =', diff2)

diff1 = [-2 -1  3  6]
diff2 = [-2 -1  3  6]


In [23]:
# sum
sum1 = a + b
print('sum1 =', sum1)
sum2 = np.add(a, b)
print('sum2 =', sum2)

sum1 = [4 9 9 8]
sum2 = [4 9 9 8]


In [24]:
# sin
print('sin(a) =', np.sin(a))
# cos
print('cos(a) =', np.cos(a))
# log
print('log(a) =', np.log(a))

sin(a) = [ 0.84147098 -0.7568025  -0.2794155   0.6569866 ]
cos(a) = [ 0.54030231 -0.65364362  0.96017029  0.75390225]
log(a) = [0.         1.38629436 1.79175947 1.94591015]


In [25]:
# dot product
a.dot(b)

48

In [26]:
a == b

array([False, False, False, False])

In [27]:
a > 3

array([False,  True,  True,  True])

#### Aggregate functions

In [42]:
# average
a.mean()

# min
a.min()

# max
a.max()

# corrcoef
np.corrcoef(a, b)

np.std(a)

2.29128784747792

### Subsetting, Slicing and Indexing

In [19]:
arr1 = np.array([1, 4, 6, 7])
# arr2 = np.array([3, 5, 3, 1])
arr3 = np.array([[1.5, 2, 3], [4, 5, 6]])
arr4 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [11]:
arr4.shape

(2, 2, 3)

In [21]:
# accessing items in a 1D array
arr1[2]

# accessing items in 2D array
arr3[0, 2]

# accessing in a 3D array
arr4[0, 2, 1]

8

In [43]:
# slicing 1D array
arr1[0:3]

# slicing a 2D array
arr3[1, 0:2]

# slicing a 3D array
first = arr4[0, 2]
second = arr4[1, 0]

print(np.concatenate((first, second)))

[ 7  8  9 10 11 12]


In [50]:
# boolean indexing
arr1[arr1 < 5]

array([1, 4])

## Array manipulation

In [53]:
print(arr3)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [54]:
# transpose
# arr3_transpose = np.transpose(arr3) 
arr3_transpose = arr3.T
print(arr3_transpose)

[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]


In [ ]:
# combining arrays
first = arr4[0, 2]
second = arr4[1, 0]

print(np.concatenate((first, second)))

In [ ]:
# stacking
np.vstack((a,b))
np.hstack((a,b))
np.column_stack((a,b))
np.c_[a, b]

In [ ]:
# splitting arrays
np.hsplit()
np.vsplit()