In [ ]:
!pip install torch

In [7]:
import torch
import numpy as np
import pandas as pd

## Creating Tensors

In [5]:
data = [[12, 200], [30, 4000]]

x_data = torch.tensor(data)

In [6]:
x_data

tensor([[  12,  200],
        [  30, 4000]])

In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[  12,  200],
        [  30, 4000]])

In [9]:
x_ones = torch.ones_like(x_np)
x_ones

tensor([[1, 1],
        [1, 1]])

In [14]:
shape = (2, 3)

rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.2338, 0.1436, 0.8507],
        [0.8137, 0.4382, 0.4563]])

In [15]:
ones_tensor = torch.ones(shape)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
zeros_tensor = torch.zeros(shape)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## Tensor Attributes

In [17]:
tensor_ = torch.rand(3, 3)

In [18]:
tensor_

tensor([[0.0395, 0.2699, 0.0760],
        [0.8109, 0.1625, 0.9366],
        [0.4921, 0.0884, 0.5562]])

In [19]:
tensor_.shape

torch.Size([3, 3])

In [20]:
tensor_.dtype

torch.float32

## Operations on Tensors

In [23]:
tensor_ = torch.rand(4, 4)
tensor_

tensor([[0.4992, 0.8771, 0.1229, 0.9377],
        [0.8887, 0.8682, 0.3100, 0.4700],
        [0.1371, 0.7604, 0.1291, 0.3892],
        [0.9708, 0.3269, 0.5685, 0.4741]])

### Indexing and Slicing

In [31]:
# get row
tensor_[0]

tensor([0.4992, 0.8771, 0.1229, 0.9377])

In [32]:
# get a row
tensor_[-1]

tensor([0.9708, 0.3269, 0.5685, 0.4741])

In [27]:
# get a column
tensor_[:, 0]

tensor([0.4992, 0.8887, 0.1371, 0.9708])

In [29]:
tensor_[..., -2]

tensor([0.1229, 0.3100, 0.1291, 0.5685])

**Exercise:**

- How can you join two or more tesors along a given dimension?

## Arithmetic Operations

In [42]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[2, 3], [4, 5]])

print(tensor1)
print(tensor2)

tensor([[1, 2],
        [3, 4]])
tensor([[2, 3],
        [4, 5]])


### Multiplication

In [39]:
product = tensor1 * tensor2
product

tensor([[ 2,  6],
        [12, 20]])

In [40]:
tensor1.mul(tensor2)

tensor([[ 2,  6],
        [12, 20]])

In [41]:
tensor1 @ tensor2

tensor([[10, 13],
        [22, 29]])

In [43]:
tensor1.matmul(tensor2)

tensor([[10, 13],
        [22, 29]])

In [45]:
sum_ = tensor1.sum()

In [47]:
print(sum_)

tensor(10)


In [49]:
sum_.item()

10

**Exercise:**

- What are In-place operations, demonstrate with some examples.

## Bridge with Numpy

In [50]:
tensor3 = torch.ones(5)

In [52]:
numpy_arr = tensor3.numpy()

In [53]:
tensor3.add_(1)

tensor([2., 2., 2., 2., 2.])

In [54]:
numpy_arr

array([2., 2., 2., 2., 2.], dtype=float32)